
package com.bohu.nucleichealth;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RasClientDetail", targetNamespace = "http://report.dagene.net/", wsdlLocation = "http://report.dalabs.cn/RasClientDetail.asmx?WSDL")
public class RasClientDetail
    extends Service
{

    private final static URL RASCLIENTDETAIL_WSDL_LOCATION;
    private final static WebServiceException RASCLIENTDETAIL_EXCEPTION;
    private final static QName RASCLIENTDETAIL_QNAME = new QName("http://report.dagene.net/", "RasClientDetail");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://report.dalabs.cn/RasClientDetail.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RASCLIENTDETAIL_WSDL_LOCATION = url;
        RASCLIENTDETAIL_EXCEPTION = e;
    }

    public RasClientDetail() {
        super(__getWsdlLocation(), RASCLIENTDETAIL_QNAME);
    }

    public RasClientDetail(WebServiceFeature... features) {
        super(__getWsdlLocation(), RASCLIENTDETAIL_QNAME, features);
    }

    public RasClientDetail(URL wsdlLocation) {
        super(wsdlLocation, RASCLIENTDETAIL_QNAME);
    }

    public RasClientDetail(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RASCLIENTDETAIL_QNAME, features);
    }

    public RasClientDetail(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RasClientDetail(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RasClientDetailSoap
     */
    @WebEndpoint(name = "RasClientDetailSoap")
public RasClientDetailSoap getRasClientDetailSoap() {
        return super.getPort(new QName("http://report.dagene.net/", "RasClientDetailSoap"), RasClientDetailSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RasClientDetailSoap
     */
    @WebEndpoint(name = "RasClientDetailSoap")
    public RasClientDetailSoap getRasClientDetailSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://report.dagene.net/", "RasClientDetailSoap"), RasClientDetailSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RASCLIENTDETAIL_EXCEPTION!= null) {
            throw RASCLIENTDETAIL_EXCEPTION;
        }
        return RASCLIENTDETAIL_WSDL_LOCATION;
    }

}
